---
abstract: 'Combine several images into a single CSS sprite'
author:
  - 'Savio Dimatteo <savio@lokku.com>'
build_requires:
  Config::Simple: 0
  Cwd: 0
  File::Basename: 0
  File::Find::Rule: 0
  File::Path: 0
  File::Spec: 0
  File::Temp: 0
  File::Touch: 0
  Test::CheckManifest: 0
  Test::File: 1.33
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CSS-SpriteMaker
provides:
  CSS::SpriteMaker:
    file: lib/CSS/SpriteMaker.pm
    version: 0.15
  CSS::SpriteMaker::Layout:
    file: lib/CSS/SpriteMaker/Layout.pm
    version: 0.04
  CSS::SpriteMaker::Layout::DirectoryBased:
    file: lib/CSS/SpriteMaker/Layout/DirectoryBased.pm
    version: 0.02
  CSS::SpriteMaker::Layout::FixedDimension:
    file: lib/CSS/SpriteMaker/Layout/FixedDimension.pm
    version: 0.02
  CSS::SpriteMaker::Layout::Packed:
    file: lib/CSS/SpriteMaker/Layout/Packed.pm
    version: 0.02
  CSS::SpriteMaker::Layout::Packed::Node:
    file: lib/CSS/SpriteMaker/Layout/Packed/Node.pm
    version: 0.01
requires:
  File::Find: 0
  Getopt::Long: 0
  Image::Magick: 0
  Module::Pluggable: 0
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.15
